#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { JSDOM } from 'jsdom';
import MarkdownIt from 'markdown-it';
import hljs from 'highlight.js';

// ── Themes ──────────────────────────────────────────────────────────────────
const THEMES = [
  { id: 'apple', name: 'Mac', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.7!important;color:#1d1d1f!important;background-color:#ffffff!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#111!important;line-height:1.3!important;margin:38px 0 16px;letter-spacing:-0.015em;', h2:'font-size:26px;font-weight:600;color:#111!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#1d1d1f!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#1d1d1f!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#1d1d1f!important;', strong:'font-weight:700;color:#000!important;', em:'font-style:italic;color:#666!important;', a:'color:#0066cc!important;text-decoration:none;border-bottom:1px solid #0066cc;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#1d1d1f!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#f5f5f7!important;border-left:4px solid #0066cc;color:#555!important;border-radius:4px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#f5f5f7!important;color:#0066cc!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#f5f5f7!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#eaeaea!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:12px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f5f5f7!important;padding:12px 16px;text-align:left;font-weight:600;color:#1d1d1f!important;border:1px solid #e0e0e0;', td:'padding:12px 16px;border:1px solid #e0e0e0;color:#1d1d1f!important;', tr:'border:none;' }},
  { id: 'claude', name: 'Claude', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.7!important;color:#2b2b2b!important;background-color:#f8f6f0!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#b75c3d!important;line-height:1.3!important;margin:38px 0 16px;letter-spacing:-0.015em;', h2:'font-size:26px;font-weight:600;color:#b75c3d!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#2b2b2b!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#2b2b2b!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#2b2b2b!important;', strong:'font-weight:700;color:#b75c3d!important;background-color:rgba(183,92,61,0.08);padding:0 4px;border-radius:4px;', em:'font-style:italic;color:#666!important;', a:'color:#b75c3d!important;text-decoration:none;border-bottom:1px solid #b75c3d;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#2b2b2b!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:rgba(183,92,61,0.04)!important;border-left:4px solid #b75c3d;color:#555!important;border-radius:4px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#f0ece4!important;color:#b75c3d!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#f0ece4!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#eaeaea!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:4px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f0ece4!important;padding:12px 16px;text-align:left;font-weight:600;color:#2b2b2b!important;border:1px solid #e0ddd6;', td:'padding:12px 16px;border:1px solid #e0ddd6;color:#2b2b2b!important;', tr:'border:none;' }},
  { id: 'wechat', name: '微信原生', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.7!important;color:#333333!important;background-color:#ffffff!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#111!important;line-height:1.3!important;margin:38px 0 16px;', h2:'font-size:26px;font-weight:600;color:#111!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#333333!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#333333!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#333333!important;', strong:'font-weight:700;color:#07c160!important;background-color:rgba(7,193,96,0.08);padding:0 4px;border-radius:4px;', em:'font-style:italic;color:#666!important;', a:'color:#07c160!important;text-decoration:none;border-bottom:1px solid #07c160;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#333333!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#f0f7f2!important;border-left:4px solid #07c160;color:#555!important;border-radius:4px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#f0f7f2!important;color:#07c160!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#f0f7f2!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#eaeaea!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:4px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f0f7f2!important;padding:12px 16px;text-align:left;font-weight:600;color:#333333!important;border:1px solid #d8e8dc;', td:'padding:12px 16px;border:1px solid #d8e8dc;color:#333333!important;', tr:'border:none;' }},
  { id: 'media', name: 'NYT', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:Georgia,"Times New Roman",Times,serif;font-size:16px;line-height:1.7!important;color:#000000!important;background-color:#fdfaf6!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#111!important;line-height:1.3!important;margin:38px 0 16px;border-bottom:2px solid #000;padding-bottom:12px;', h2:'font-size:26px;font-weight:700;color:#111!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#000000!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#000000!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#000000!important;', strong:'font-weight:700;color:#000!important;', em:'font-style:italic;color:#666!important;', a:'color:#326891!important;text-decoration:none;border-bottom:1px solid #326891;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#000000!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#f0ede8!important;border-left:4px solid #326891;color:#555!important;border-radius:4px;font-style:italic;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#f0ede8!important;color:#326891!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#f0ede8!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#d5cfc5!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:4px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f0ede8!important;padding:12px 16px;text-align:left;font-weight:600;color:#000000!important;border:1px solid #d5cfc5;', td:'padding:12px 16px;border:1px solid #d5cfc5;color:#000000!important;', tr:'border:none;' }},
  { id: 'stripe', name: 'Stripe', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.7!important;color:#425466!important;background-color:#f6f9fc!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#111!important;line-height:1.3!important;margin:38px 0 16px;', h2:'font-size:26px;font-weight:600;color:#111!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#425466!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#425466!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#425466!important;', strong:'font-weight:700;color:#0a2540!important;', em:'font-style:italic;color:#666!important;', a:'color:#635bff!important;text-decoration:none;border-bottom:1px solid #635bff;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#425466!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#eef0ff!important;border-left:4px solid #635bff;color:#425466!important;border-radius:4px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#f0f2fe!important;color:#635bff!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#f0f2fe!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#e0e0e0!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:4px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f0f2fe!important;padding:12px 16px;text-align:left;font-weight:600;color:#425466!important;border:1px solid #dde0f0;', td:'padding:12px 16px;border:1px solid #dde0f0;color:#425466!important;', tr:'border:none;' }},
  { id: 'linear', name: 'Linear', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.7!important;color:#f1f1f2!important;background-color:#101114!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#fff!important;line-height:1.3!important;margin:38px 0 16px;', h2:'font-size:26px;font-weight:600;color:#eee!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#ddd!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#f1f1f2!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#f1f1f2!important;', strong:'font-weight:700;color:#fff!important;', em:'font-style:italic;color:#bbb!important;', a:'color:#5e6ad2!important;text-decoration:none;border-bottom:1px solid #5e6ad2;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#f1f1f2!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#1a1a1a!important;border-left:4px solid #5e6ad2;color:#ccc!important;border-radius:4px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#1a1a2e!important;color:#5e6ad2!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#1a1a2e!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#333!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:4px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#1a1a2e!important;padding:12px 16px;text-align:left;font-weight:600;color:#f1f1f2!important;border:1px solid #333;', td:'padding:12px 16px;border:1px solid #333;color:#f1f1f2!important;', tr:'border:none;' }},
  { id: 'notion', name: 'Notion', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.6!important;color:#37352f!important;background-color:#ffffff!important;word-wrap:break-word;', h1:'font-size:34px;font-weight:700;color:#37352f!important;line-height:1.2!important;margin:38px 0 8px;letter-spacing:-0.02em;', h2:'font-size:26px;font-weight:600;color:#37352f!important;line-height:1.3!important;margin:32px 0 8px;', h3:'font-size:21px;font-weight:600;color:#37352f!important;line-height:1.35!important;margin:28px 0 8px;', h4:'font-size:18px;font-weight:600;color:#37352f!important;line-height:1.4!important;margin:24px 0 8px;', p:'margin:4px 0!important;line-height:1.6!important;color:#37352f!important;', strong:'font-weight:700;color:#37352f!important;', em:'font-style:italic;color:#37352f!important;', a:'color:#37352f!important;text-decoration:underline;text-underline-offset:3px;text-decoration-color:rgba(55,53,47,0.4);', ul:'margin:4px 0;padding-left:26px;', ol:'margin:4px 0;padding-left:26px;', li:'margin:2px 0;line-height:1.6!important;color:#37352f!important;', blockquote:'margin:8px 0;padding:4px 16px;background-color:transparent!important;border-left:3px solid #37352f;color:#37352f!important;border-radius:0;', code:'font-family:"SF Mono",Consolas,monospace;padding:2px 5px;background-color:#f7f6f3!important;color:#eb5757!important;border-radius:3px;font-size:13px!important;line-height:1.5!important;', pre:'margin:16px 0;padding:20px;background-color:#f7f6f3!important;border-radius:4px;overflow-x:auto;font-size:13px!important;line-height:1.5!important;', hr:'margin:24px auto;border:none;height:1px;background-color:#e9e9e7!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:16px auto;border-radius:2px;', table:'width:100%;margin:16px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f7f6f3!important;padding:8px 12px;text-align:left;font-weight:600;color:#37352f!important;border:1px solid #e9e9e7;', td:'padding:8px 12px;border:1px solid #e9e9e7;color:#37352f!important;', tr:'border:none;' }},
  { id: 'github', name: 'GitHub', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6!important;color:#1f2328!important;background-color:#ffffff!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:600;color:#1f2328!important;line-height:1.25!important;margin:24px 0 16px;padding-bottom:10px;border-bottom:1px solid #d1d9e0;', h2:'font-size:24px;font-weight:600;color:#1f2328!important;line-height:1.25!important;margin:24px 0 16px;padding-bottom:8px;border-bottom:1px solid #d1d9e0;', h3:'font-size:20px;font-weight:600;color:#1f2328!important;line-height:1.25!important;margin:24px 0 16px;', h4:'font-size:16px;font-weight:600;color:#1f2328!important;line-height:1.25!important;margin:24px 0 16px;', p:'margin:16px 0!important;line-height:1.6!important;color:#1f2328!important;', strong:'font-weight:600;color:#1f2328!important;', em:'font-style:italic;color:#1f2328!important;', a:'color:#0969da!important;text-decoration:underline;text-underline-offset:2px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:4px 0;line-height:1.6!important;color:#1f2328!important;', blockquote:'margin:16px 0;padding:8px 16px;background-color:transparent!important;border-left:4px solid #d0d7de;color:#656d76!important;border-radius:0;', code:'font-family:"SF Mono",Consolas,"Liberation Mono",Menlo,monospace;padding:3px 6px;background-color:rgba(175,184,193,0.2)!important;color:#1f2328!important;border-radius:6px;font-size:13px!important;line-height:1.5!important;', pre:'margin:16px 0;padding:16px;background-color:#f6f8fa!important;border-radius:6px;overflow-x:auto;font-size:13px!important;line-height:1.45!important;', hr:'margin:24px auto;border:none;height:3px;background-color:#d1d9e0!important;width:100%;border-radius:2px;', img:'max-width:100%;height:auto;display:block;margin:16px auto;border-radius:6px;', table:'width:100%;margin:16px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#f6f8fa!important;padding:8px 16px;text-align:left;font-weight:600;color:#1f2328!important;border:1px solid #d1d9e0;', td:'padding:8px 16px;border:1px solid #d1d9e0;color:#1f2328!important;', tr:'border:none;' }},
  { id: 'dracula', name: 'Dracula', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.7!important;color:#f8f8f2!important;background-color:#282a36!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#bd93f9!important;line-height:1.3!important;margin:38px 0 16px;', h2:'font-size:26px;font-weight:600;color:#ff79c6!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#8be9fd!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#50fa7b!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#f8f8f2!important;', strong:'font-weight:700;color:#ffb86c!important;', em:'font-style:italic;color:#8be9fd!important;', a:'color:#8be9fd!important;text-decoration:none;border-bottom:1px solid #8be9fd;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#f8f8f2!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#44475a!important;border-left:4px solid #bd93f9;color:#f8f8f2!important;border-radius:4px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#44475a!important;color:#50fa7b!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#44475a!important;border-radius:8px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#6272a4!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:4px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#44475a!important;padding:12px 16px;text-align:left;font-weight:600;color:#bd93f9!important;border:1px solid #6272a4;', td:'padding:12px 16px;border:1px solid #6272a4;color:#f8f8f2!important;', tr:'border:none;' }},
  { id: 'sakura', name: '樱花', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:16px;line-height:1.75!important;color:#4a3f4f!important;background-color:#fef7f9!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#c44569!important;line-height:1.3!important;margin:38px 0 16px;', h2:'font-size:26px;font-weight:600;color:#c44569!important;line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#4a3f4f!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#4a3f4f!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.75!important;color:#4a3f4f!important;', strong:'font-weight:700;color:#c44569!important;background-color:rgba(196,69,105,0.06);padding:0 4px;border-radius:4px;', em:'font-style:italic;color:#9b7fa7!important;', a:'color:#c44569!important;text-decoration:none;border-bottom:1px solid rgba(196,69,105,0.3);padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.75!important;color:#4a3f4f!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#fceef2!important;border-left:4px solid #e8a0b4;color:#6b5570!important;border-radius:8px;', code:'font-family:"SF Mono",Consolas,monospace;padding:3px 6px;background-color:#fceef2!important;color:#c44569!important;border-radius:4px;font-size:12px!important;line-height:1.5!important;', pre:'margin:24px 0;padding:20px;background-color:#fceef2!important;border-radius:12px;overflow-x:auto;font-size:12px!important;line-height:1.5!important;', hr:'margin:36px auto;border:none;height:1px;background-color:#f0d4dd!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:12px;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:15px;', th:'background-color:#fceef2!important;padding:12px 16px;text-align:left;font-weight:600;color:#4a3f4f!important;border:1px solid #f0d4dd;', td:'padding:12px 16px;border:1px solid #f0d4dd;color:#4a3f4f!important;', tr:'border:none;' }},
  { id: 'cyberpunk', name: 'Cyberpunk', styles: { container: 'max-width:100%;margin:0 auto;padding:24px 20px 48px 20px;font-family:"SF Mono","Fira Code",Consolas,monospace;font-size:15px;line-height:1.7!important;color:#e0e0ff!important;background-color:#0d0221!important;word-wrap:break-word;', h1:'font-size:32px;font-weight:700;color:#ff2a6d!important;text-shadow:0 0 8px rgba(255,42,109,0.5);line-height:1.3!important;margin:38px 0 16px;text-transform:uppercase;', h2:'font-size:26px;font-weight:600;color:#05d9e8!important;text-shadow:0 0 8px rgba(5,217,232,0.5);line-height:1.35!important;margin:32px 0 16px;', h3:'font-size:21px;font-weight:600;color:#d1f7ff!important;line-height:1.4!important;margin:28px 0 14px;', h4:'font-size:18px;font-weight:600;color:#ff2a6d!important;line-height:1.4!important;margin:24px 0 12px;', p:'margin:18px 0!important;line-height:1.7!important;color:#e0e0ff!important;', strong:'font-weight:700;color:#ff2a6d!important;text-shadow:0 0 6px rgba(255,42,109,0.4);', em:'font-style:italic;color:#05d9e8!important;', a:'color:#05d9e8!important;text-decoration:none;border-bottom:1px solid #05d9e8;padding-bottom:1px;', ul:'margin:16px 0;padding-left:28px;', ol:'margin:16px 0;padding-left:28px;', li:'margin:8px 0;line-height:1.7!important;color:#e0e0ff!important;', blockquote:'margin:24px 0;padding:16px 20px;background-color:#1a0a3e!important;border-left:4px solid #ff2a6d;color:#c8c8ff!important;border-radius:0;', code:'font-family:"SF Mono","Fira Code",Consolas,monospace;padding:3px 6px;background-color:#1a0a3e!important;color:#05d9e8!important;border-radius:0;font-size:13px!important;line-height:1.5!important;border:1px solid #2a1a4e;', pre:'margin:24px 0;padding:20px;background-color:#1a0a3e!important;border-radius:0;overflow-x:auto;font-size:13px!important;line-height:1.5!important;border:1px solid #2a1a4e;', hr:'margin:36px auto;border:none;height:2px;background:linear-gradient(90deg,#ff2a6d,#05d9e8)!important;width:100%;', img:'max-width:100%;height:auto;display:block;margin:24px auto;border-radius:0;', table:'width:100%;margin:24px 0;border-collapse:collapse;font-size:14px;', th:'background-color:#1a0a3e!important;padding:12px 16px;text-align:left;font-weight:600;color:#ff2a6d!important;border:1px solid #2a1a4e;', td:'padding:12px 16px;border:1px solid #2a1a4e;color:#e0e0ff!important;', tr:'border:none;' }},
];

// ── Markdown setup ──────────────────────────────────────────────────────────
const md = new MarkdownIt({
  html: true, linkify: true, typographer: false,
  highlight(str, lang) {
    let code = '';
    if (lang && hljs.getLanguage(lang)) {
      try { code = hljs.highlight(str, { language: lang }).value; } catch { code = md.utils.escapeHtml(str); }
    } else { code = md.utils.escapeHtml(str); }
    const dots = '<div style="margin-bottom:12px;white-space:nowrap;"><span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:#ff5f56;margin-right:6px;"></span><span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:#ffbd2e;margin-right:6px;"></span><span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:#27c93f;"></span></div>';
    return `<pre>${dots}<code class="hljs">${code}</code></pre>`;
  }
});

function preprocessMarkdown(content) {
  content = content.replace(/^[ ]{0,3}(\*[ ]*\*[ ]*\*[\* ]*)[ \t]*$/gm, '***');
  content = content.replace(/^[ ]{0,3}(-[ ]*-[ ]*-[- ]*)[ \t]*$/gm, '---');
  content = content.replace(/^[ ]{0,3}(_[ ]*_[ ]*_[_ ]*)[ \t]*$/gm, '___');
  content = content.replace(/\*\*[ \t]+\*\*/g, ' ');
  content = content.replace(/\*{4,}/g, '');
  content = content.replace(/([^\s])\*\*([+\-＋－%％~～!！?？,，.。:：;；、\\/|@#￥$^&*_=（）()【】\[\]《》〈〉「」『』"""'`…·][^\n*]*?)\*\*/g, '$1**​$2**');
  return content;
}

// ── Apply theme ─────────────────────────────────────────────────────────────
function applyTheme(html, themeId) {
  const theme = THEMES.find(t => t.id === themeId) || THEMES[0];
  const style = theme.styles;
  const dom = new JSDOM(html);
  const doc = dom.window.document;

  Object.keys(style).forEach(selector => {
    if (selector === 'container' || selector === 'pre code') return;
    doc.querySelectorAll(selector).forEach(el => {
      if (selector === 'code' && el.parentElement?.tagName === 'PRE') return;
      const cs = el.getAttribute('style') || '';
      el.setAttribute('style', cs + '; ' + style[selector]);
    });
  });

  // List markers
  doc.querySelectorAll('ul').forEach(ul => { const s = ul.getAttribute('style')||''; ul.setAttribute('style', `${s}; list-style-type:disc!important;list-style-position:outside;`); });
  doc.querySelectorAll('ol').forEach(ol => { const s = ol.getAttribute('style')||''; ol.setAttribute('style', `${s}; list-style-type:decimal!important;list-style-position:outside;`); });

  // Code highlight tokens
  const hljsColors = { 'hljs-comment':'color:#6a737d;', 'hljs-keyword':'color:#d73a49;font-weight:600;', 'hljs-string':'color:#032f62;', 'hljs-title':'color:#6f42c1;font-weight:600;', 'hljs-type':'color:#005cc5;font-weight:600;', 'hljs-number':'color:#005cc5;', 'hljs-built_in':'color:#005cc5;', 'hljs-variable':'color:#e36209;', 'hljs-tag':'color:#22863a;', 'hljs-name':'color:#22863a;', 'hljs-attr':'color:#6f42c1;', 'hljs-literal':'color:#005cc5;', 'hljs-section':'color:#6f42c1;font-weight:600;' };
  doc.querySelectorAll('.hljs span').forEach(span => {
    let s = span.getAttribute('style') || '';
    span.classList.forEach(cls => { if (hljsColors[cls]) s += hljsColors[cls]; });
    if (s) span.setAttribute('style', s);
  });

  doc.querySelectorAll('pre').forEach(pre => { const s = pre.getAttribute('style')||''; pre.setAttribute('style', `${s};font-variant-ligatures:none;tab-size:2;`); });
  doc.querySelectorAll('pre code, .hljs').forEach(c => { const s = c.getAttribute('style')||''; c.setAttribute('style', `${s};display:block;font-size:inherit!important;line-height:inherit!important;white-space:pre;word-break:normal;overflow-wrap:normal;`); });

  // Heading inline overrides
  const overrides = { strong:'font-weight:700;color:inherit!important;background-color:transparent!important;', em:'font-style:italic;color:inherit!important;', a:'color:inherit!important;text-decoration:none!important;border-bottom:1px solid currentColor!important;background-color:transparent!important;', code:'color:inherit!important;background-color:transparent!important;border:none!important;padding:0!important;' };
  doc.querySelectorAll('h1,h2,h3,h4,h5,h6').forEach(h => {
    Object.keys(overrides).forEach(tag => { h.querySelectorAll(tag).forEach(n => { n.setAttribute('style', `${n.getAttribute('style')||''};${overrides[tag]}`); }); });
  });

  const container = doc.createElement('div');
  container.setAttribute('style', style.container);
  container.innerHTML = doc.body.innerHTML;
  return container.outerHTML;
}

// ── WeChat compat ───────────────────────────────────────────────────────────
function makeWeChatCompatible(html, themeId) {
  const theme = THEMES.find(t => t.id === themeId) || THEMES[0];
  const containerStyle = theme.styles.container || '';
  const dom = new JSDOM(html);
  const doc = dom.window.document;

  const rootNodes = Array.from(doc.body.children);
  const section = doc.createElement('section');
  section.setAttribute('style', containerStyle);
  rootNodes.forEach(node => {
    if (node.tagName === 'DIV' && rootNodes.length === 1) {
      Array.from(node.childNodes).forEach(child => section.appendChild(child));
    } else { section.appendChild(node); }
  });

  // Flatten li > p
  section.querySelectorAll('li').forEach(li => {
    li.querySelectorAll('p').forEach(p => {
      const span = doc.createElement('span');
      span.innerHTML = p.innerHTML;
      const ps = p.getAttribute('style');
      if (ps) span.setAttribute('style', ps);
      p.parentNode?.replaceChild(span, p);
    });
  });

  // Font inheritance
  const fontMatch = containerStyle.match(/font-family:\s*([^;]+);/);
  const sizeMatch = containerStyle.match(/font-size:\s*([^;]+);/);
  const colorMatch = containerStyle.match(/color:\s*([^;]+?)(?:\s*!important)?;/);
  const lhMatch = containerStyle.match(/line-height:\s*([^;]+);/);
  section.querySelectorAll('p,li,h1,h2,h3,h4,h5,h6,blockquote,span').forEach(node => {
    if (node.tagName === 'SPAN' && node.closest('pre,code')) return;
    let cs = node.getAttribute('style') || '';
    if (fontMatch && !cs.includes('font-family:')) cs += ` font-family:${fontMatch[1]};`;
    if (lhMatch && !cs.includes('line-height:')) cs += ` line-height:${lhMatch[1]};`;
    if (sizeMatch && !cs.includes('font-size:') && ['P','LI','BLOCKQUOTE','SPAN'].includes(node.tagName)) cs += ` font-size:${sizeMatch[1]};`;
    if (colorMatch && !cs.includes('color:')) cs += ` color:${colorMatch[1]};`;
    node.setAttribute('style', cs.trim());
  });

  // CJK punctuation
  section.querySelectorAll('strong,b,em,span,a,code').forEach(node => {
    const next = node.nextSibling;
    if (!next || next.nodeType !== 3) return;
    const text = next.textContent || '';
    const match = text.match(/^\s*([：；，。！？、:])(.*)$/s);
    if (!match) return;
    node.appendChild(doc.createTextNode(match[1]));
    if (match[2]) next.textContent = match[2];
    else next.parentNode?.removeChild(next);
  });

  doc.body.innerHTML = '';
  doc.body.appendChild(section);
  return doc.body.innerHTML;
}

// ── Main ────────────────────────────────────────────────────────────────────
const [,, filePath, themeId = 'apple'] = process.argv;
if (!filePath) {
  console.error('用法: node convert.mjs <file.md> [themeId]');
  console.error('可用主题: ' + THEMES.map(t => t.id).join(', '));
  process.exit(1);
}

const content = readFileSync(filePath, 'utf-8');
const rawHtml = md.render(preprocessMarkdown(content));
const styledHtml = applyTheme(rawHtml, themeId);
const finalHtml = makeWeChatCompatible(styledHtml, themeId);

writeFileSync('/tmp/md2wechat-output.html', finalHtml, 'utf-8');
process.stdout.write(finalHtml);
